package com.hundsun.hot.portfolio.mapper;

import com.hundsun.hot.portfolio.model.MaxDrawDown;
import java.util.List;

public interface MaxDrawDownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_max_draw_down
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    int deleteByPrimaryKey(String stockCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_max_draw_down
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    int insert(MaxDrawDown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_max_draw_down
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    MaxDrawDown selectByPrimaryKey(String stockCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_max_draw_down
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    List<MaxDrawDown> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_max_draw_down
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    int updateByPrimaryKey(MaxDrawDown record);
}