package com.hundsun.hot.portfolio.mapper;

import com.hundsun.hot.portfolio.model.SharpRatio;
import java.util.List;

public interface SharpRatioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_sharp_ratio
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    int deleteByPrimaryKey(String stockCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_sharp_ratio
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    int insert(SharpRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_sharp_ratio
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    SharpRatio selectByPrimaryKey(String stockCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_sharp_ratio
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    List<SharpRatio> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_sharp_ratio
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    int updateByPrimaryKey(SharpRatio record);
}