package com.hundsun.hot.portfolio.mapper;

import com.hundsun.hot.portfolio.model.StockBaseInfo;
import java.util.List;

public interface StockBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_base_info
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    int deleteByPrimaryKey(String stockCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_base_info
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    int insert(StockBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_base_info
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    StockBaseInfo selectByPrimaryKey(String stockCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_base_info
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    List<StockBaseInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_base_info
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    int updateByPrimaryKey(StockBaseInfo record);
}