package com.hundsun.hot.portfolio.mapper;

import com.hundsun.hot.portfolio.model.SumEarnings;
import java.util.List;

public interface SumEarningsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_sum_earnings
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    int deleteByPrimaryKey(String stockCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_sum_earnings
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    int insert(SumEarnings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_sum_earnings
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    SumEarnings selectByPrimaryKey(String stockCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_sum_earnings
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    List<SumEarnings> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_sum_earnings
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    int updateByPrimaryKey(SumEarnings record);
}