package com.hundsun.hot.portfolio.mapper;

import com.hundsun.hot.portfolio.model.VarRatio;
import java.util.List;

public interface VarRatioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_var_ratio
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    int deleteByPrimaryKey(String stockCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_var_ratio
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    int insert(VarRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_var_ratio
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    VarRatio selectByPrimaryKey(String stockCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_var_ratio
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    List<VarRatio> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_var_ratio
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    int updateByPrimaryKey(VarRatio record);
}