package com.hundsun.hot.portfolio.model;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

public class FluctuationRatio {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_fluctuation_ratio.stock_code
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private String stockCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_fluctuation_ratio.fluctuation_ratio_20
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double fluctuationRatio20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_fluctuation_ratio.fluctuation_ratio_120
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double fluctuationRatio120;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_fluctuation_ratio.fluctuation_ratio_250
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double fluctuationRatio250;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_fluctuation_ratio.fluctuation_ratio_500
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double fluctuationRatio500;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_fluctuation_ratio.stock_code
     *
     * @return the value of t_stock_fluctuation_ratio.stock_code
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_fluctuation_ratio.stock_code
     *
     * @param stockCode the value for t_stock_fluctuation_ratio.stock_code
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_fluctuation_ratio.fluctuation_ratio_20
     *
     * @return the value of t_stock_fluctuation_ratio.fluctuation_ratio_20
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getFluctuationRatio20() {
        return fluctuationRatio20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_fluctuation_ratio.fluctuation_ratio_20
     *
     * @param fluctuationRatio20 the value for t_stock_fluctuation_ratio.fluctuation_ratio_20
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setFluctuationRatio20(Double fluctuationRatio20) {
        this.fluctuationRatio20 = fluctuationRatio20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_fluctuation_ratio.fluctuation_ratio_120
     *
     * @return the value of t_stock_fluctuation_ratio.fluctuation_ratio_120
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getFluctuationRatio120() {
        return fluctuationRatio120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_fluctuation_ratio.fluctuation_ratio_120
     *
     * @param fluctuationRatio120 the value for t_stock_fluctuation_ratio.fluctuation_ratio_120
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setFluctuationRatio120(Double fluctuationRatio120) {
        this.fluctuationRatio120 = fluctuationRatio120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_fluctuation_ratio.fluctuation_ratio_250
     *
     * @return the value of t_stock_fluctuation_ratio.fluctuation_ratio_250
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getFluctuationRatio250() {
        return fluctuationRatio250;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_fluctuation_ratio.fluctuation_ratio_250
     *
     * @param fluctuationRatio250 the value for t_stock_fluctuation_ratio.fluctuation_ratio_250
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setFluctuationRatio250(Double fluctuationRatio250) {
        this.fluctuationRatio250 = fluctuationRatio250;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_fluctuation_ratio.fluctuation_ratio_500
     *
     * @return the value of t_stock_fluctuation_ratio.fluctuation_ratio_500
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getFluctuationRatio500() {
        return fluctuationRatio500;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_fluctuation_ratio.fluctuation_ratio_500
     *
     * @param fluctuationRatio500 the value for t_stock_fluctuation_ratio.fluctuation_ratio_500
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setFluctuationRatio500(Double fluctuationRatio500) {
        this.fluctuationRatio500 = fluctuationRatio500;
    }
    
	@Override
	public int hashCode() {
		return HashCodeBuilder.reflectionHashCode(this);
	}

	@Override
	public boolean equals(Object obj) {
		return EqualsBuilder.reflectionEquals(this, obj);
	}
	
    @Override
    public String toString(){
    	return ToStringBuilder.reflectionToString(this);
    }
}