package com.hundsun.hot.portfolio.model;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

public class MaxDrawDown {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_max_draw_down.stock_code
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private String stockCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_max_draw_down.max_draw_down_20
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double maxDrawDown20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_max_draw_down.max_draw_down_120
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double maxDrawDown120;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_max_draw_down.max_draw_down_250
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double maxDrawDown250;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_max_draw_down.max_draw_down_500
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double maxDrawDown500;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_max_draw_down.stock_code
     *
     * @return the value of t_stock_max_draw_down.stock_code
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_max_draw_down.stock_code
     *
     * @param stockCode the value for t_stock_max_draw_down.stock_code
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_max_draw_down.max_draw_down_20
     *
     * @return the value of t_stock_max_draw_down.max_draw_down_20
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getMaxDrawDown20() {
        return maxDrawDown20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_max_draw_down.max_draw_down_20
     *
     * @param maxDrawDown20 the value for t_stock_max_draw_down.max_draw_down_20
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setMaxDrawDown20(Double maxDrawDown20) {
        this.maxDrawDown20 = maxDrawDown20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_max_draw_down.max_draw_down_120
     *
     * @return the value of t_stock_max_draw_down.max_draw_down_120
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getMaxDrawDown120() {
        return maxDrawDown120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_max_draw_down.max_draw_down_120
     *
     * @param maxDrawDown120 the value for t_stock_max_draw_down.max_draw_down_120
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setMaxDrawDown120(Double maxDrawDown120) {
        this.maxDrawDown120 = maxDrawDown120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_max_draw_down.max_draw_down_250
     *
     * @return the value of t_stock_max_draw_down.max_draw_down_250
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getMaxDrawDown250() {
        return maxDrawDown250;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_max_draw_down.max_draw_down_250
     *
     * @param maxDrawDown250 the value for t_stock_max_draw_down.max_draw_down_250
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setMaxDrawDown250(Double maxDrawDown250) {
        this.maxDrawDown250 = maxDrawDown250;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_max_draw_down.max_draw_down_500
     *
     * @return the value of t_stock_max_draw_down.max_draw_down_500
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getMaxDrawDown500() {
        return maxDrawDown500;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_max_draw_down.max_draw_down_500
     *
     * @param maxDrawDown500 the value for t_stock_max_draw_down.max_draw_down_500
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setMaxDrawDown500(Double maxDrawDown500) {
        this.maxDrawDown500 = maxDrawDown500;
    }
    
	@Override
	public int hashCode() {
		return HashCodeBuilder.reflectionHashCode(this);
	}

	@Override
	public boolean equals(Object obj) {
		return EqualsBuilder.reflectionEquals(this, obj);
	}
	
    @Override
    public String toString(){
    	return ToStringBuilder.reflectionToString(this);
    }
}