package com.hundsun.hot.portfolio.model;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

public class SharpRatio {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_sharp_ratio.stock_code
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private String stockCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_sharp_ratio.sharp_ratio_20
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double sharpRatio20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_sharp_ratio.sharp_ratio_120
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double sharpRatio120;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_sharp_ratio.sharp_ratio_250
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double sharpRatio250;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_sharp_ratio.sharp_ratio_500
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double sharpRatio500;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_sharp_ratio.stock_code
     *
     * @return the value of t_stock_sharp_ratio.stock_code
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_sharp_ratio.stock_code
     *
     * @param stockCode the value for t_stock_sharp_ratio.stock_code
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_sharp_ratio.sharp_ratio_20
     *
     * @return the value of t_stock_sharp_ratio.sharp_ratio_20
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getSharpRatio20() {
        return sharpRatio20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_sharp_ratio.sharp_ratio_20
     *
     * @param sharpRatio20 the value for t_stock_sharp_ratio.sharp_ratio_20
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setSharpRatio20(Double sharpRatio20) {
        this.sharpRatio20 = sharpRatio20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_sharp_ratio.sharp_ratio_120
     *
     * @return the value of t_stock_sharp_ratio.sharp_ratio_120
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getSharpRatio120() {
        return sharpRatio120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_sharp_ratio.sharp_ratio_120
     *
     * @param sharpRatio120 the value for t_stock_sharp_ratio.sharp_ratio_120
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setSharpRatio120(Double sharpRatio120) {
        this.sharpRatio120 = sharpRatio120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_sharp_ratio.sharp_ratio_250
     *
     * @return the value of t_stock_sharp_ratio.sharp_ratio_250
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getSharpRatio250() {
        return sharpRatio250;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_sharp_ratio.sharp_ratio_250
     *
     * @param sharpRatio250 the value for t_stock_sharp_ratio.sharp_ratio_250
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setSharpRatio250(Double sharpRatio250) {
        this.sharpRatio250 = sharpRatio250;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_sharp_ratio.sharp_ratio_500
     *
     * @return the value of t_stock_sharp_ratio.sharp_ratio_500
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getSharpRatio500() {
        return sharpRatio500;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_sharp_ratio.sharp_ratio_500
     *
     * @param sharpRatio500 the value for t_stock_sharp_ratio.sharp_ratio_500
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setSharpRatio500(Double sharpRatio500) {
        this.sharpRatio500 = sharpRatio500;
    }
    
	@Override
	public int hashCode() {
		return HashCodeBuilder.reflectionHashCode(this);
	}

	@Override
	public boolean equals(Object obj) {
		return EqualsBuilder.reflectionEquals(this, obj);
	}
	
    @Override
    public String toString(){
    	return ToStringBuilder.reflectionToString(this);
    }
}