package com.hundsun.hot.portfolio.model;

public class StockBaseInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_base_info.stock_code
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    private String stockCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_base_info.market
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    private String market;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_base_info.stock_name
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    private String stockName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_base_info.industry_code
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    private String industryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_base_info.industry_type
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    private String industryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_base_info.industry_name
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    private String industryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_base_info.trade_status
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    private Integer tradeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_base_info.stock_code
     *
     * @return the value of t_stock_base_info.stock_code
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_base_info.stock_code
     *
     * @param stockCode the value for t_stock_base_info.stock_code
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_base_info.market
     *
     * @return the value of t_stock_base_info.market
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_base_info.market
     *
     * @param market the value for t_stock_base_info.market
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public void setMarket(String market) {
        this.market = market == null ? null : market.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_base_info.stock_name
     *
     * @return the value of t_stock_base_info.stock_name
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_base_info.stock_name
     *
     * @param stockName the value for t_stock_base_info.stock_name
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_base_info.industry_code
     *
     * @return the value of t_stock_base_info.industry_code
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public String getIndustryCode() {
        return industryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_base_info.industry_code
     *
     * @param industryCode the value for t_stock_base_info.industry_code
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public void setIndustryCode(String industryCode) {
        this.industryCode = industryCode == null ? null : industryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_base_info.industry_type
     *
     * @return the value of t_stock_base_info.industry_type
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public String getIndustryType() {
        return industryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_base_info.industry_type
     *
     * @param industryType the value for t_stock_base_info.industry_type
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public void setIndustryType(String industryType) {
        this.industryType = industryType == null ? null : industryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_base_info.industry_name
     *
     * @return the value of t_stock_base_info.industry_name
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public String getIndustryName() {
        return industryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_base_info.industry_name
     *
     * @param industryName the value for t_stock_base_info.industry_name
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public void setIndustryName(String industryName) {
        this.industryName = industryName == null ? null : industryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_base_info.trade_status
     *
     * @return the value of t_stock_base_info.trade_status
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public Integer getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_base_info.trade_status
     *
     * @param tradeStatus the value for t_stock_base_info.trade_status
     *
     * @mbg.generated Mon Nov 21 10:27:07 CST 2016
     */
    public void setTradeStatus(Integer tradeStatus) {
        this.tradeStatus = tradeStatus;
    }
}