package com.hundsun.hot.portfolio.model;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

public class SumEarnings {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_sum_earnings.stock_code
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private String stockCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_sum_earnings.sum_earnings_20
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double sumEarnings20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_sum_earnings.sum_earnings_120
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double sumEarnings120;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_sum_earnings.sum_earnings_250
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double sumEarnings250;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_sum_earnings.sum_earnings_500
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    private Double sumEarnings500;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_sum_earnings.stock_code
     *
     * @return the value of t_stock_sum_earnings.stock_code
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_sum_earnings.stock_code
     *
     * @param stockCode the value for t_stock_sum_earnings.stock_code
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_sum_earnings.sum_earnings_20
     *
     * @return the value of t_stock_sum_earnings.sum_earnings_20
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getSumEarnings20() {
        return sumEarnings20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_sum_earnings.sum_earnings_20
     *
     * @param sumEarnings20 the value for t_stock_sum_earnings.sum_earnings_20
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setSumEarnings20(Double sumEarnings20) {
        this.sumEarnings20 = sumEarnings20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_sum_earnings.sum_earnings_120
     *
     * @return the value of t_stock_sum_earnings.sum_earnings_120
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getSumEarnings120() {
        return sumEarnings120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_sum_earnings.sum_earnings_120
     *
     * @param sumEarnings120 the value for t_stock_sum_earnings.sum_earnings_120
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setSumEarnings120(Double sumEarnings120) {
        this.sumEarnings120 = sumEarnings120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_sum_earnings.sum_earnings_250
     *
     * @return the value of t_stock_sum_earnings.sum_earnings_250
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getSumEarnings250() {
        return sumEarnings250;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_sum_earnings.sum_earnings_250
     *
     * @param sumEarnings250 the value for t_stock_sum_earnings.sum_earnings_250
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setSumEarnings250(Double sumEarnings250) {
        this.sumEarnings250 = sumEarnings250;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_sum_earnings.sum_earnings_500
     *
     * @return the value of t_stock_sum_earnings.sum_earnings_500
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public Double getSumEarnings500() {
        return sumEarnings500;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_sum_earnings.sum_earnings_500
     *
     * @param sumEarnings500 the value for t_stock_sum_earnings.sum_earnings_500
     *
     * @mbg.generated Tue Oct 18 16:28:59 CST 2016
     */
    public void setSumEarnings500(Double sumEarnings500) {
        this.sumEarnings500 = sumEarnings500;
    }
    
	@Override
	public int hashCode() {
		return HashCodeBuilder.reflectionHashCode(this);
	}

	@Override
	public boolean equals(Object obj) {
		return EqualsBuilder.reflectionEquals(this, obj);
	}
	
    @Override
    public String toString(){
    	return ToStringBuilder.reflectionToString(this);
    }
}