package com.hundsun.hot.portfolio.model;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_id
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_acco
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    private String userAcco;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.password
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_name
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.work_id
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    private Integer workId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.wechat_id
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    private String wechatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.phone_num
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    private Integer phoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.email
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.status
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_id
     *
     * @return the value of t_user_info.user_id
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_id
     *
     * @param userId the value for t_user_info.user_id
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_acco
     *
     * @return the value of t_user_info.user_acco
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public String getUserAcco() {
        return userAcco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_acco
     *
     * @param userAcco the value for t_user_info.user_acco
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public void setUserAcco(String userAcco) {
        this.userAcco = userAcco == null ? null : userAcco.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.password
     *
     * @return the value of t_user_info.password
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.password
     *
     * @param password the value for t_user_info.password
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_name
     *
     * @return the value of t_user_info.user_name
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_name
     *
     * @param userName the value for t_user_info.user_name
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.work_id
     *
     * @return the value of t_user_info.work_id
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.work_id
     *
     * @param workId the value for t_user_info.work_id
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.wechat_id
     *
     * @return the value of t_user_info.wechat_id
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.wechat_id
     *
     * @param wechatId the value for t_user_info.wechat_id
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId == null ? null : wechatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.phone_num
     *
     * @return the value of t_user_info.phone_num
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public Integer getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.phone_num
     *
     * @param phoneNum the value for t_user_info.phone_num
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public void setPhoneNum(Integer phoneNum) {
        this.phoneNum = phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.email
     *
     * @return the value of t_user_info.email
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.email
     *
     * @param email the value for t_user_info.email
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.status
     *
     * @return the value of t_user_info.status
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.status
     *
     * @param status the value for t_user_info.status
     *
     * @mbg.generated Wed Nov 16 14:03:29 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
    
	@Override
	public int hashCode() {
		return HashCodeBuilder.reflectionHashCode(this);
	}

	@Override
	public boolean equals(Object obj) {
		return EqualsBuilder.reflectionEquals(this, obj);
	}
	
    @Override
    public String toString(){
    	return ToStringBuilder.reflectionToString(this);
    }
}